## 訓練LSTM模型

In [2]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('./df_merged.csv')
display(df)

,建物現況格局-房,建物現況格局-廳,建物現況格局-衛,建物現況格局-隔間,有無管理組織,單價元平方公尺,電梯,預售屋,建築完成距今,鄉鎮市區_中山區,...,移轉層次-數字,建物型態_住宅大樓(11層含以上有電梯),建物型態_公寓(5樓含以下無電梯),建物型態_其他,建物型態_套房(1房1廳1衛),建物型態_店面(店鋪),建物型態_廠辦,建物型態_華廈(10層含以下有電梯),建物型態_辦公商業大樓,建物型態_透天厝
0,1,1,1,1,1,178092,0,0,26.000000,0,...,5,1,0,0,0,0,0,0,0,0
1,5,4,3,1,1,139426,0,0,36.000000,0,...,0,0,0,0,0,0,0,0,0,1
2,4,1,1,1,0,106824,0,0,54.000000,0,...,1,0,1,0,0,0,0,0,0,0
3,3,2,2,1,0,110159,0,0,14.508063,0,...,4,0,1,0,0,0,0,0,0,0
4,1,1,1,1,1,204499,0,0,2.000000,0,...,8,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55637,0,0,0,0,0,284434,0,1,0.000000,0,...,4,0,0,1,0,0,0,0,0,0
55638,2,1,1,1,0,387364,1,1,0.000000,0,...,4,0,0,0,0,0,0,1,0,0
55639,3,2,2,1,0,354202,1,1,0.000000,0,...,3,1,0,0,0,0,0,0,0,0
55640,1,1,1,1,0,387161,1,1,0.000000,0,...,8,0,0,0,0,0,0,1,0,0
55641,3,2,2,1,0,378342,1,1,0.000000,1,...,18,1,0,0,0,0,0,0,0,0

In [4]:
df.columns

Index(['建物現況格局-房', '建物現況格局-廳', '建物現況格局-衛', '建物現況格局-隔間', '有無管理組織', '單價元平方公尺',
       '電梯', '預售屋', '建築完成距今', '鄉鎮市區_中山區', '鄉鎮市區_中正區', '鄉鎮市區_信義區', '鄉鎮市區_內湖區',
       '鄉鎮市區_北投區', '鄉鎮市區_南港區', '鄉鎮市區_士林區', '鄉鎮市區_大同區', '鄉鎮市區_大安區', '鄉鎮市區_文山區',
       '鄉鎮市區_松山區', '鄉鎮市區_萬華區', '交易土地', '交易建物', '交易車位', '交易距今', '路段', '移轉層次-數字',
       '建物型態_住宅大樓(11層含以上有電梯)', '建物型態_公寓(5樓含以下無電梯)', '建物型態_其他',
       '建物型態_套房(1房1廳1衛)', '建物型態_店面(店鋪)', '建物型態_廠辦', '建物型態_華廈(10層含以下有電梯)',
       '建物型態_辦公商業大樓', '建物型態_透天厝'],
      dtype='object')

In [6]:
X = df.drop('單價元平方公尺', axis=1)  # 刪除 '單價元平方公尺' 欄位，其餘欄位為目標變數
y = df['單價元平方公尺']
display(X)

,建物現況格局-房,建物現況格局-廳,建物現況格局-衛,建物現況格局-隔間,有無管理組織,電梯,預售屋,建築完成距今,鄉鎮市區_中山區,鄉鎮市區_中正區,...,移轉層次-數字,建物型態_住宅大樓(11層含以上有電梯),建物型態_公寓(5樓含以下無電梯),建物型態_其他,建物型態_套房(1房1廳1衛),建物型態_店面(店鋪),建物型態_廠辦,建物型態_華廈(10層含以下有電梯),建物型態_辦公商業大樓,建物型態_透天厝
0,1,1,1,1,1,0,0,26.000000,0,0,...,5,1,0,0,0,0,0,0,0,0
1,5,4,3,1,1,0,0,36.000000,0,0,...,0,0,0,0,0,0,0,0,0,1
2,4,1,1,1,0,0,0,54.000000,0,0,...,1,0,1,0,0,0,0,0,0,0
3,3,2,2,1,0,0,0,14.508063,0,0,...,4,0,1,0,0,0,0,0,0,0
4,1,1,1,1,1,0,0,2.000000,0,0,...,8,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55637,0,0,0,0,0,0,1,0.000000,0,0,...,4,0,0,1,0,0,0,0,0,0
55638,2,1,1,1,0,1,1,0.000000,0,0,...,4,0,0,0,0,0,0,1,0,0
55639,3,2,2,1,0,1,1,0.000000,0,0,...,3,1,0,0,0,0,0,0,0,0
55640,1,1,1,1,0,1,1,0.000000,0,0,...,8,0,0,0,0,0,0,1,0,0
55641,3,2,2,1,0,1,1,0.000000,1,0,...,18,1,0,0,0,0,0,0,0,0

In [31]:
X_train, X_test_val, y_train, y_test_val = train_test_split(X, y, test_size=0.2, random_state=23)
X_test, X_val, y_test, y_val = train_test_split(X_test_val, y_test_val, test_size=0.5, random_state=23)

In [32]:
# 定義模型
model = Sequential()
model.add(LSTM(units=64, input_shape=(X_train.shape[1], 1)))  # 設定LSTM的輸入形狀，timesteps是時間步數，input_dim是輸入特徵的維度
model.add(Dense(1))  # 輸出層只有一個節點，對應目標變數的預測值

# 編譯模型
model.compile(loss='mean_squared_error', optimizer='adam')

# 訓練模型
model.fit(X_train, y_train, epochs=10, batch_size=32)

# 使用模型進行預測
y_pred_val = model.predict(X_val)

Epoch 1/10
1392/1392 [==============================] - 13s 8ms/step - loss: 3634440175616.0000
Epoch 2/10
1392/1392 [==============================] - 12s 8ms/step - loss: 3634413961216.0000
Epoch 3/10
1392/1392 [==============================] - 12s 8ms/step - loss: 3634384338944.0000
Epoch 4/10
1392/1392 [==============================] - 12s 9ms/step - loss: 3634360745984.0000
Epoch 5/10
1392/1392 [==============================] - 12s 8ms/step - loss: 3634340298752.0000
Epoch 6/10
1392/1392 [==============================] - 12s 8ms/step - loss: 3634313297920.0000
Epoch 7/10
1392/1392 [==============================] - 12s 8ms/step - loss: 3634286559232.0000
Epoch 8/10
1392/1392 [==============================] - 12s 9ms/step - loss: 3634268471296.0000
Epoch 9/10
1392/1392 [==============================] - 12s 9ms/step - loss: 3634243043328.0000
Epoch 10/10
1392/1392 [==============================] - 12s 9ms/step - loss: 3634216828928.0000
174/174 [==============================] - 1s 3ms/step

In [33]:
# 計算MSE
mse = mean_squared_error(y_val, y_pred_val)
print("mse:", mse)

# 計算RMSE
rmse = mean_squared_error(y_val, y_pred_val, squared=False)
print("rmse:", rmse)

mse: 57237424423.21181
rmse: 239243.44175590648

In [34]:
# 使用模型進行預測
y_pred = model.predict(X_test)

174/174 [==============================] - 1s 3ms/step

In [35]:
# 計算MSE
mse = mean_squared_error(y_test, y_pred)
print("mse:", mse)

# 計算RMSE
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("rmse:", rmse)

mse: 61621004155.271454
rmse: 248235.78339004927

In [37]:
model.save('LSTM.h5') #儲存模型

/opt/homebrew/Caskroom/miniconda/base/envs/ML/lib/python3.10/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

## 成果（預測房價）

In [36]:
df_road = pd.read_csv('./df_road.csv')
display(df_road)

     Unnamed: 0  整數數字
0           NaN   966
1           一壽街   189
2           一德街   904
3           一江街   967
4           三元街   965
...         ...   ...
1230     龍泉段一小段   566
1231     龍泉段三小段   560
1232     龍泉段二小段  1139
1233        龍泉街  1139
1234        NaN  1139

[1235 rows x 2 columns]

In [52]:
def changeRoadToNum(input_road):
    if not df_road[df_road['Unnamed: 0'] == input_road].empty:
        return df_road[df_road['Unnamed: 0'] == input_road].iloc[0, 1]
    else:
        return -1

changeRoadToNum('龍泉段一小段')

566

In [57]:
def changeAreaToNum(input_area):
    areas = ['中山區', '中正區', '信義區', '內湖區',
             '北投區', '南港區', '士林區',
             '大同區', '大安區', '文山區', '松山區', '萬華區']
    values = [1 if area == input_area else 0 for area in areas]
    return values

print(changeAreaToNum('中山區'))

def changeBuildingToNum(input_building):
    buildings = ['住宅大樓(11層含以上有電梯)', '公寓(5樓含以下無電梯)', '其他', '套房(1房1廳1衛)',
                '店面(店鋪)', '廠辦', '華廈(10層含以下有電梯)','辦公商業大樓', '透天厝']
    values = [1 if building == input_building else 0 for building in buildings]
    return values

print(changeBuildingToNum('住宅大樓(11層含以上有電梯)'))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0]

In [60]:
# '建物現況格局-房', '建物現況格局-廳', '建物現況格局-衛', '建物現況格局-隔間', '有無管理組織',
# '電梯', '預售屋', '建築完成距今',
# '鄉鎮市區_中山區', '鄉鎮市區_中正區','鄉鎮市區_信義區', '鄉鎮市區_內湖區','鄉鎮市區_北投區', '鄉鎮市區_南港區', '鄉鎮市區_士林區', '鄉鎮市區_大同區', '鄉鎮市區_大安區', '鄉鎮市區_文山區', '鄉鎮市區_松山區', '鄉鎮市區_萬華區',
# '交易土地', '交易建物', '交易車位', '交易距今', '路段',
# '移轉層次-數字',
#'建物型態_住宅大樓(11層含以上有電梯)', '建物型態_公寓(5樓含以下無電梯)', '建物型態_其他', '建物型態_套房(1房1廳1衛)', '建物型態_店面(店鋪)', '建物型態_廠辦', '建物型態_華廈(10層含以下有電梯)','建物型態_辦公商業大樓', '建物型態_透天厝'

from tensorflow.keras.models import load_model
new_data = np.array([2, 1, 2, 1, 1,
                     1, 0, 10,
                     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 1, 0, 0, 566,
                     10,
                     1, 0, 0, 0, 0, 0, 0, 0, 0
                     ])
new_data = new_data.reshape(1, X_train.shape[1], 1)
model_new = load_model('./LSTM.h5')
prediction = model_new.predict(new_data)
print(prediction)

1/1 [==============================] - 0s 214ms/step
[[553.446]]